[package]
name = "sum_check_protocol"
version = "0.1.0"
authors = ["Mario <mario.moliner@gmail.com>"]
edition = "2021"


[dependencies]
ark-ff = "0.3.0"
ark-poly = "0.3.0"
ark-bls12-381 = "0.3.0"
ark-std = "0.3.0"


